title: Hello, there
author: Yufeng Luo
email: brookluo1997@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Working in progress
# social links
# twitter_username: your-twitter-handle
github_username:  Brookluo
markdown: kramdown
show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
 - README.md
 - RNS_stability.md
